//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.Utilities {
    
    
    public partial class LogWindow {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.Utilities.LogWindow
            this.Name = "MonoDevelop.TaskForce.Utilities.LogWindow";
            this.Title = Mono.Unix.Catalog.GetString("LogWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
