// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.Gui.Components {
    
    
    public partial class SessionDisplayWidget {
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView sessionView1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.Gui.Components.SessionDisplayWidget
            Stetic.BinContainer.Attach(this);
            this.HeightRequest = 200;
            this.Name = "MonoDevelop.TaskForce.Gui.Components.SessionDisplayWidget";
            // Container child MonoDevelop.TaskForce.Gui.Components.SessionDisplayWidget.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.sessionView1 = new Gtk.TreeView();
            this.sessionView1.HeightRequest = 105;
            this.sessionView1.CanFocus = true;
            this.sessionView1.Name = "sessionView1";
            this.GtkScrolledWindow.Add(this.sessionView1);
            this.Add(this.GtkScrolledWindow);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
