// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.Gui.Components {
    
    
    public partial class CommentWidget {
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView commentTree;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TextView contentView;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Button replyButton;
        
        private Gtk.Button quoteButton;
        
        private Gtk.Button newComment;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.Gui.Components.CommentWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.TaskForce.Gui.Components.CommentWidget";
            // Container child MonoDevelop.TaskForce.Gui.Components.CommentWidget.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.commentTree = new Gtk.TreeView();
            this.commentTree.CanFocus = true;
            this.commentTree.Name = "commentTree";
            this.GtkScrolledWindow.Add(this.commentTree);
            this.hbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
            w2.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.contentView = new Gtk.TextView();
            this.contentView.CanFocus = true;
            this.contentView.Name = "contentView";
            this.GtkScrolledWindow1.Add(this.contentView);
            this.hbox1.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow1]));
            w4.Position = 1;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.replyButton = new Gtk.Button();
            this.replyButton.CanFocus = true;
            this.replyButton.Name = "replyButton";
            this.replyButton.UseUnderline = true;
            // Container child replyButton.Gtk.Container+ContainerChild
            Gtk.Alignment w5 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w6 = new Gtk.HBox();
            w6.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w7 = new Gtk.Image();
            w7.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-redo", Gtk.IconSize.Menu, 16);
            w6.Add(w7);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w9 = new Gtk.Label();
            w9.LabelProp = Mono.Unix.Catalog.GetString("Reply");
            w9.UseUnderline = true;
            w6.Add(w9);
            w5.Add(w6);
            this.replyButton.Add(w5);
            this.vbox1.Add(this.replyButton);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.replyButton]));
            w13.Position = 0;
            w13.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.quoteButton = new Gtk.Button();
            this.quoteButton.CanFocus = true;
            this.quoteButton.Name = "quoteButton";
            this.quoteButton.UseUnderline = true;
            // Container child quoteButton.Gtk.Container+ContainerChild
            Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w15 = new Gtk.HBox();
            w15.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w16 = new Gtk.Image();
            w16.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Menu, 16);
            w15.Add(w16);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w18 = new Gtk.Label();
            w18.LabelProp = Mono.Unix.Catalog.GetString("Quote and Reply");
            w18.UseUnderline = true;
            w15.Add(w18);
            w14.Add(w15);
            this.quoteButton.Add(w14);
            this.vbox1.Add(this.quoteButton);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox1[this.quoteButton]));
            w22.Position = 1;
            w22.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.newComment = new Gtk.Button();
            this.newComment.CanFocus = true;
            this.newComment.Name = "newComment";
            this.newComment.UseUnderline = true;
            // Container child newComment.Gtk.Container+ContainerChild
            Gtk.Alignment w23 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w24 = new Gtk.HBox();
            w24.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w25 = new Gtk.Image();
            w25.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-new", Gtk.IconSize.Menu, 16);
            w24.Add(w25);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w27 = new Gtk.Label();
            w27.LabelProp = Mono.Unix.Catalog.GetString("New Comment");
            w27.UseUnderline = true;
            w24.Add(w27);
            w23.Add(w24);
            this.newComment.Add(w23);
            this.vbox1.Add(this.newComment);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox1[this.newComment]));
            w31.Position = 2;
            w31.Fill = false;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w32.Position = 2;
            w32.Expand = false;
            w32.Fill = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
