// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.Gui.Components {
    
    
    public partial class CommentWidget2 {
        
        private Gtk.VBox vbox1;
        
        private Gtk.VBox commentVBox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.Gui.Components.CommentWidget2
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.TaskForce.Gui.Components.CommentWidget2";
            // Container child MonoDevelop.TaskForce.Gui.Components.CommentWidget2.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.commentVBox = new Gtk.VBox();
            this.commentVBox.Name = "commentVBox";
            this.commentVBox.Spacing = 6;
            this.vbox1.Add(this.commentVBox);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.commentVBox]));
            w1.Position = 0;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
