// 
// NodeDataSkeleton.cs
//  
// Author:
//       Anirudh Sanjeev <anirudh@anirudhsanjeev.org>
// 
// Copyright (c) 2009 Anirudh Sanjeev
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using MonoDevelop.TaskForce.Utilities;
using System.Collections;

namespace MonoDevelop.TaskForce.Data
{
	public delegate void NodeDataChangedHandler(NodeData source, NodeDataChangedEventArgs args);
	
	public abstract class NodeData
	{		
		public NodeData()
		{
			children = new ArrayList();
		}
		
		public abstract NodeType nodeType
		{
			get;
		}
		
		public NodeData parent;
		public ArrayList children;
		
		public override bool CanMakeChild(NodeType childType);
		public override bool CanMakeChild(NodeData childData);
		
		public virtual void AddChild(NodeData childData)
		{
			// Check if this node can have this as a child
			if(CanMakeChild(childData))
			{
				// First, remove the child from it's parent list
				childData.parent.children.Remove(childData);
				
				// set the child data's parent to the current object
				childData.parent = this;
				
				// add the child data as a child
				this.children.Add(childData);
				
				// Inform both classes about the updates
			}
		}
		
		/// <summary>
		/// Triggered when a node is changed
		/// </summary>
		public event NodeDataChangedHandler NodeDataChanged;
		
		public virtual void TriggerUpdate()
		{
			// Todo: Add args somewhere?
			
			NodeDataChangedEventArgs args = new NodeDataChangedEventArgs();			
			NodeDataChanged(this, args);
		}
	}
	
	public class NodeDataChangedEventArgs
	{
		public NodeDataChangedEventArgs()
		{
			
		}
	}
}
