// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.LocalProvider.Gui {
    
    
    public partial class TaskViewWidget {
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button activateButton;
        
        private Gtk.Button button2;
        
        private Gtk.Button button3;
        
        private Gtk.Table table1;
        
        private MonoDevelop.TaskForce.Gui.Components.CommentWidget2 commentwidget21;
        
        private Gtk.Entry dueDateEntry;
        
        private Gtk.ScrolledWindow GtkScrolledWindow2;
        
        private Gtk.TextView descriptionTextView;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Entry nameEntry;
        
        private Gtk.ComboBox priorityCombo;
        
        private MonoDevelop.TaskForce.Gui.Components.SessionDisplayWidget sessiondisplaywidget1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.LocalProvider.Gui.TaskViewWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.TaskForce.LocalProvider.Gui.TaskViewWidget";
            // Container child MonoDevelop.TaskForce.LocalProvider.Gui.TaskViewWidget.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.activateButton = new Gtk.Button();
            this.activateButton.CanFocus = true;
            this.activateButton.Name = "activateButton";
            this.activateButton.UseUnderline = true;
            // Container child activateButton.Gtk.Container+ContainerChild
            Gtk.Alignment w2 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w3 = new Gtk.HBox();
            w3.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w4 = new Gtk.Image();
            w4.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.LargeToolbar, 24);
            w3.Add(w4);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w6 = new Gtk.Label();
            w6.LabelProp = Mono.Unix.Catalog.GetString("Activate Task");
            w6.UseUnderline = true;
            w3.Add(w6);
            w2.Add(w3);
            this.activateButton.Add(w2);
            this.hbox3.Add(this.activateButton);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.activateButton]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button2 = new Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            // Container child button2.Gtk.Container+ContainerChild
            Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w12 = new Gtk.HBox();
            w12.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w13 = new Gtk.Image();
            w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-convert", Gtk.IconSize.Menu, 16);
            w12.Add(w13);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w15 = new Gtk.Label();
            w15.LabelProp = Mono.Unix.Catalog.GetString("View Context (Inactive)");
            w15.UseUnderline = true;
            w12.Add(w15);
            w11.Add(w12);
            this.button2.Add(w11);
            this.hbox3.Add(this.button2);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox3[this.button2]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button3 = new Gtk.Button();
            this.button3.CanFocus = true;
            this.button3.Name = "button3";
            this.button3.UseUnderline = true;
            // Container child button3.Gtk.Container+ContainerChild
            Gtk.Alignment w20 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w21 = new Gtk.HBox();
            w21.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w22 = new Gtk.Image();
            w22.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Menu, 16);
            w21.Add(w22);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w24 = new Gtk.Label();
            w24.LabelProp = Mono.Unix.Catalog.GetString("Create Patch (Inactive)");
            w24.UseUnderline = true;
            w21.Add(w24);
            w20.Add(w21);
            this.button3.Add(w20);
            this.hbox3.Add(this.button3);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.hbox3[this.button3]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w29.Position = 0;
            w29.Expand = false;
            w29.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(15));
            // Container child table1.Gtk.Table+TableChild
            this.commentwidget21 = new MonoDevelop.TaskForce.Gui.Components.CommentWidget2();
            this.commentwidget21.Events = ((Gdk.EventMask)(256));
            this.commentwidget21.Name = "commentwidget21";
            this.table1.Add(this.commentwidget21);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.commentwidget21]));
            w30.TopAttach = ((uint)(4));
            w30.BottomAttach = ((uint)(5));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.dueDateEntry = new Gtk.Entry();
            this.dueDateEntry.CanFocus = true;
            this.dueDateEntry.Name = "dueDateEntry";
            this.dueDateEntry.Text = Mono.Unix.Catalog.GetString("Not implemented");
            this.dueDateEntry.IsEditable = true;
            this.dueDateEntry.InvisibleChar = '•';
            this.table1.Add(this.dueDateEntry);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.dueDateEntry]));
            w31.TopAttach = ((uint)(3));
            w31.BottomAttach = ((uint)(4));
            w31.LeftAttach = ((uint)(1));
            w31.RightAttach = ((uint)(2));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.GtkScrolledWindow2 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
            this.GtkScrolledWindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
            this.descriptionTextView = new Gtk.TextView();
            this.descriptionTextView.WidthRequest = 360;
            this.descriptionTextView.HeightRequest = 175;
            this.descriptionTextView.CanFocus = true;
            this.descriptionTextView.Name = "descriptionTextView";
            this.descriptionTextView.WrapMode = ((Gtk.WrapMode)(2));
            this.GtkScrolledWindow2.Add(this.descriptionTextView);
            this.table1.Add(this.GtkScrolledWindow2);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow2]));
            w33.TopAttach = ((uint)(1));
            w33.BottomAttach = ((uint)(2));
            w33.LeftAttach = ((uint)(1));
            w33.RightAttach = ((uint)(2));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.Yalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Sessions");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w34.TopAttach = ((uint)(5));
            w34.BottomAttach = ((uint)(6));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.Yalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Description");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w35.TopAttach = ((uint)(1));
            w35.BottomAttach = ((uint)(2));
            w35.XOptions = ((Gtk.AttachOptions)(4));
            w35.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.Yalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Priority");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w36.TopAttach = ((uint)(2));
            w36.BottomAttach = ((uint)(3));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.WidthRequest = 73;
            this.label4.Name = "label4";
            this.label4.Xalign = 0.05F;
            this.label4.Yalign = 0.02F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Comments");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w37.TopAttach = ((uint)(4));
            w37.BottomAttach = ((uint)(5));
            w37.XOptions = ((Gtk.AttachOptions)(4));
            w37.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.Yalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Name");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w38.XOptions = ((Gtk.AttachOptions)(4));
            w38.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.Yalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Due");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w39.TopAttach = ((uint)(3));
            w39.BottomAttach = ((uint)(4));
            w39.XOptions = ((Gtk.AttachOptions)(4));
            w39.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.nameEntry = new Gtk.Entry();
            this.nameEntry.CanFocus = true;
            this.nameEntry.Name = "nameEntry";
            this.nameEntry.IsEditable = true;
            this.nameEntry.InvisibleChar = '•';
            this.table1.Add(this.nameEntry);
            Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table1[this.nameEntry]));
            w40.LeftAttach = ((uint)(1));
            w40.RightAttach = ((uint)(2));
            w40.XOptions = ((Gtk.AttachOptions)(4));
            w40.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.priorityCombo = Gtk.ComboBox.NewText();
            this.priorityCombo.AppendText(Mono.Unix.Catalog.GetString("Minor"));
            this.priorityCombo.AppendText(Mono.Unix.Catalog.GetString("Normal"));
            this.priorityCombo.AppendText(Mono.Unix.Catalog.GetString("Major"));
            this.priorityCombo.AppendText(Mono.Unix.Catalog.GetString("Urgent"));
            this.priorityCombo.AppendText(Mono.Unix.Catalog.GetString("Critical"));
            this.priorityCombo.AppendText("");
            this.priorityCombo.Name = "priorityCombo";
            this.priorityCombo.Active = 1;
            this.table1.Add(this.priorityCombo);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table1[this.priorityCombo]));
            w41.TopAttach = ((uint)(2));
            w41.BottomAttach = ((uint)(3));
            w41.LeftAttach = ((uint)(1));
            w41.RightAttach = ((uint)(2));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.sessiondisplaywidget1 = new MonoDevelop.TaskForce.Gui.Components.SessionDisplayWidget();
            this.sessiondisplaywidget1.HeightRequest = 120;
            this.sessiondisplaywidget1.Events = ((Gdk.EventMask)(256));
            this.sessiondisplaywidget1.Name = "sessiondisplaywidget1";
            this.table1.Add(this.sessiondisplaywidget1);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table1[this.sessiondisplaywidget1]));
            w42.TopAttach = ((uint)(5));
            w42.BottomAttach = ((uint)(6));
            w42.LeftAttach = ((uint)(1));
            w42.RightAttach = ((uint)(2));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w43.Position = 1;
            w43.Expand = false;
            w43.Fill = false;
            w1.Add(this.vbox1);
            this.scrolledwindow1.Add(w1);
            this.Add(this.scrolledwindow1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
