// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.LocalProvider.Gui {
    
    
    public partial class NewCategory {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Entry categoryName;
        
        private Gtk.Button button1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.LocalProvider.Gui.NewCategory
            this.Name = "MonoDevelop.TaskForce.LocalProvider.Gui.NewCategory";
            this.Title = Mono.Unix.Catalog.GetString("NewCategory");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child MonoDevelop.TaskForce.LocalProvider.Gui.NewCategory.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("label1");
            this.vbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.categoryName = new Gtk.Entry();
            this.categoryName.CanFocus = true;
            this.categoryName.Name = "categoryName";
            this.categoryName.IsEditable = true;
            this.categoryName.InvisibleChar = '●';
            this.vbox1.Add(this.categoryName);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.categoryName]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Label = Mono.Unix.Catalog.GetString("button1");
            this.vbox1.Add(this.button1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.button1]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        }
    }
}
