// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.TaskForce.LocalProvider.TaskWidgets {
    
    
    public partial class EditTaskWidget {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Entry taskNameEntry;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView taskDescText;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label3;
        
        private Gtk.SpinButton prioritySpin;
        
        private Gtk.Label label4;
        
        private Gtk.Calendar dueDateCal;
        
        private MonoDevelop.TaskForce.Gui.Components.CommentWidget2 commentWidget2;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Button applyButton;
        
        private Gtk.Button button1;
        
        private Gtk.Button button2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.TaskForce.LocalProvider.TaskWidgets.EditTaskWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.TaskForce.LocalProvider.TaskWidgets.EditTaskWidget";
            // Container child MonoDevelop.TaskForce.LocalProvider.TaskWidgets.EditTaskWidget.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Name");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.taskNameEntry = new Gtk.Entry();
            this.taskNameEntry.CanFocus = true;
            this.taskNameEntry.Name = "taskNameEntry";
            this.taskNameEntry.IsEditable = true;
            this.taskNameEntry.InvisibleChar = '●';
            this.hbox1.Add(this.taskNameEntry);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.taskNameEntry]));
            w2.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Description");
            this.hbox2.Add(this.label2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.taskDescText = new Gtk.TextView();
            this.taskDescText.CanFocus = true;
            this.taskDescText.Name = "taskDescText";
            this.GtkScrolledWindow.Add(this.taskDescText);
            this.hbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
            w6.Position = 1;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Priority");
            this.hbox3.Add(this.label3);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.prioritySpin = new Gtk.SpinButton(0, 100, 1);
            this.prioritySpin.CanFocus = true;
            this.prioritySpin.Name = "prioritySpin";
            this.prioritySpin.Adjustment.PageIncrement = 10;
            this.prioritySpin.ClimbRate = 1;
            this.prioritySpin.Numeric = true;
            this.hbox3.Add(this.prioritySpin);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.prioritySpin]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("label4");
            this.hbox3.Add(this.label4);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.label4]));
            w10.Position = 2;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.dueDateCal = new Gtk.Calendar();
            this.dueDateCal.CanFocus = true;
            this.dueDateCal.Name = "dueDateCal";
            this.dueDateCal.DisplayOptions = ((Gtk.CalendarDisplayOptions)(35));
            this.hbox3.Add(this.dueDateCal);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.dueDateCal]));
            w11.Position = 3;
            w11.Expand = false;
            w11.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.commentWidget2 = new MonoDevelop.TaskForce.Gui.Components.CommentWidget2();
            this.commentWidget2.Events = ((Gdk.EventMask)(256));
            this.commentWidget2.Name = "commentWidget2";
            this.vbox1.Add(this.commentWidget2);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.commentWidget2]));
            w13.Position = 3;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.applyButton = new Gtk.Button();
            this.applyButton.CanFocus = true;
            this.applyButton.Name = "applyButton";
            this.applyButton.UseUnderline = true;
            // Container child applyButton.Gtk.Container+ContainerChild
            Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w15 = new Gtk.HBox();
            w15.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w16 = new Gtk.Image();
            w16.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w15.Add(w16);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w18 = new Gtk.Label();
            w18.LabelProp = Mono.Unix.Catalog.GetString("Apply");
            w18.UseUnderline = true;
            w15.Add(w18);
            w14.Add(w15);
            this.applyButton.Add(w14);
            this.hbox6.Add(this.applyButton);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox6[this.applyButton]));
            w22.Position = 0;
            w22.Expand = false;
            w22.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            // Container child button1.Gtk.Container+ContainerChild
            Gtk.Alignment w23 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w24 = new Gtk.HBox();
            w24.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w25 = new Gtk.Image();
            w25.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", Gtk.IconSize.Menu, 16);
            w24.Add(w25);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w27 = new Gtk.Label();
            w27.LabelProp = Mono.Unix.Catalog.GetString("Reset");
            w27.UseUnderline = true;
            w24.Add(w27);
            w23.Add(w24);
            this.button1.Add(w23);
            this.hbox6.Add(this.button1);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox6[this.button1]));
            w31.Position = 1;
            w31.Expand = false;
            w31.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.button2 = new Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            // Container child button2.Gtk.Container+ContainerChild
            Gtk.Alignment w32 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w33 = new Gtk.HBox();
            w33.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w34 = new Gtk.Image();
            w34.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            w33.Add(w34);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w36 = new Gtk.Label();
            w36.LabelProp = Mono.Unix.Catalog.GetString("Cancel");
            w36.UseUnderline = true;
            w33.Add(w36);
            w32.Add(w33);
            this.button2.Add(w32);
            this.hbox6.Add(this.button2);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.hbox6[this.button2]));
            w40.Position = 2;
            w40.Expand = false;
            w40.Fill = false;
            this.vbox1.Add(this.hbox6);
            Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
            w41.Position = 4;
            w41.Expand = false;
            w41.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.button1.Clicked += new System.EventHandler(this.OnResetButtonClicked);
        }
    }
}
